SELECT * FROM TB_MAQUINA_USUARIO;
SELECT * FROM LEITURA;
SELECT * FROM TB_USUARIO;

-- DROP TABLE TB_MAQUINA_USUARIO;

CREATE TABLE TB_MAQUINA_USUARIO (
	ID_MAQUINA_USUARIO INT IDENTITY(1,1) NOT NULL,
	NOME_SO VARCHAR(45) ,
	NOME_CPU VARCHAR(45) ,
	USO_CPU VARCHAR(45) ,
	RAM_TOTAL VARCHAR(45) ,
	RAM_DISPONIVEL VARCHAR(45) ,
	RAM_USADA VARCHAR(45) ,
	NOME_GPU VARCHAR(45) ,
	TEMP_GPU VARCHAR(45) ,
	DISCO_TOTAL VARCHAR(45) ,
	DISCO_DISPONIVEL VARCHAR(45),
	DISCO_USADO VARCHAR(45) ,
	PRIMARY KEY (ID_MAQUINA_USUARIO)
);

-- DROP TABLE TB_PROCESSOS_MAQUINA_USUARIO;
CREATE TABLE TB_PROCESSOS_MAQUINA_USUARIO (
	ID INT IDENTITY(1,1) NOT NULL,
	PID_PROCESSO INT NOT NULL,
	NOME_PROCESSO VARCHAR(45),
	USO_CPU_PROCESSO INT,
	USO_RAM_PROCESSO INT,
	PRIMARY KEY (ID)
);

--INSERT INTO TB_PROCESSOS_MAQUINA_USUARIO VALUES (1178,'JAVA',34,44);
SELECT * FROM TB_PROCESSOS_MAQUINA_USUARIO;
--DELETE FROM TB_PROCESSOS_MAQUINA_USUARIO WHERE ID = 1;
--DELETE FROM TB_PROCESSOS_MAQUINA_USUARIO ;

-- DROP TABLE TB_SERVIDOR;
CREATE TABLE TB_SERVIDOR (
	ID_SERVIDOR INT IDENTITY(1,1) NOT NULL,
	NOME_SO VARCHAR(45) ,
	NOME_CPU VARCHAR(45) ,
	USO_CPU VARCHAR(45) ,
	RAM_TOTAL VARCHAR(45) ,
	RAM_USADA VARCHAR(45) ,
	CAPACIDADE INT  ,
	STATUS VARCHAR(45) ,
--	FK_PROCESSOS_MAQ_USU INT,
--	FK_SALA_ESPERA INT,
--	FK_SALA_JOGADORES INT,
	PRIMARY KEY (ID_SERVIDOR)
);
-- DROP TABLE TB_USUARIO ;
CREATE TABLE TB_USUARIO (
	ID_USUARIO INT IDENTITY(1,1) NOT NULL,
	NOME_USU VARCHAR(45),
	EMAIL VARCHAR(45),
	SENHA VARCHAR(45),
	NIVEL_ACESSO  VARCHAR(45),
	TIPO_USUARIO  VARCHAR(45),
	PRIMARY KEY (ID_USUARIO)
);


-- DROP TABLE LEITURA ;
--CREATE TABLE LEITURA (
--	ID INT IDENTITY(1,1) NOT NULL,
--	ORIGEM VARCHAR(45),
--	VALOR INT NULL,
--	DATA_HORA DATETIME NULL,
--	PRIMARY KEY (ID)
--);


