CREATE TABLE [dbo].[TB_USUARIO_USUA]
(
	[ID_USUA_CD_USUARIO] INT NOT NULL IDENTITY (1, 1),
	[USUA_NO_USUARIO] VARCHAR(45)  NULL,
	[USUA_NO_EMAIL] NVARCHAR(45) NULL,
	[USUA_CD_SENHA] NVARCHAR(45) NULL,
	[USUA_NO_INDICACAO] VARCHAR(45)  NULL,
	[USUA_TP_USUARIO] BIT  NULL
);


/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [dbo].[TB_USUARIO_USUA] 
 ADD CONSTRAINT [PK_USUA]
	PRIMARY KEY CLUSTERED ([ID_USUA_CD_USUARIO] ASC);


/* Create Table Comments */

EXEC sp_addextendedproperty 'MS_Description', 'CRIAÇÃO da tabela para Armazenar os usuarios','Schema', [dbo], 'table', [TB_USUARIO_USUA];

-- DROP TABLE [dbo].[TB_MAQUINA_MAQU];
CREATE TABLE [dbo].[TB_MAQUINA_MAQU]
(
	[ID_MAQU_CD_MAQUINA] INT NOT NULL IDENTITY (1, 1),
	[MAQU_NO_SISTEMA_OPERACIONAL] VARCHAR(45)  NULL,
	[MAQU_NO_PROCESSADOR] VARCHAR(100)  NULL,
	[MAQU_NU_CPU_USO] INT NULL,
	[MAQU_NU_MEM_RAM_TOTAL] INT NULL,
	[MAQU_NU_MEM_RAM_USADA] INT NULL,
	[MAQU_NU_MEM_RAM_DISPONIVEL] INT NULL,
	[MAQU_NU_DISCO_TOTAL] INT NULL,
	[MAQU_NU_DISCO_USADO] INT NULL,
	[MAQU_NU_DISCO_DISPONIVEL] INT NULL,
	[MAQU_NO_GPU] VARCHAR(45)  NULL,
	[MAQU_DS_TIPO_MAQUINA] VARCHAR(45)  NULL
);
ALTER TABLE [dbo].[TB_MAQUINA_MAQU] 
 ADD CONSTRAINT [PK_MAQU]
	PRIMARY KEY CLUSTERED ([ID_MAQU_CD_MAQUINA] ASC);

EXEC sp_addextendedproperty 'MS_Description', 'CRIAÇÃO da tabela para Armazenar OS DADOS DA MAQUINA','Schema', [dbo], 'table', [TB_MAQUINA_MAQU];


CREATE TABLE [dbo].[TB_MAQUINA_USUARIO_MAUS]
(
	[ID_USUA_CD_USUARIO] INT NOT NULL,
	[ID_MAQU_CD_MAQUINA] INT NOT NULL,
	CONSTRAINT [PK_USUA_MAQU] PRIMARY KEY CLUSTERED([ID_USUA_CD_USUARIO] ASC)
	WITH (
			PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
		) ON [PRIMARY];




/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [dbo].[TB_MAQUINA_USUARIO_MAUS]  WITH CHECK ADD  CONSTRAINT [FK_USUA_MAUS] FOREIGN KEY([ID_USUA_CD_USUARIO])
REFERENCES [dbo].[TB_USUARIO_USUA] ([ID_USUA_CD_USUARIO])
ON DELETE CASCADE;


ALTER TABLE [dbo].[TB_MAQUINA_USUARIO_MAUS]  WITH CHECK ADD CONSTRAINT [FK_MAQU_MAUS] FOREIGN KEY([ID_MAQU_CD_MAQUINA])
REFERENCES [dbo].[TB_MAQUINA_MAQU] ([ID_MAQU_CD_MAQUINA])
ON DELETE CASCADE;


ALTER TABLE [dbo].[TB_MAQUINA_USUARIO_MAUS] CHECK CONSTRAINT [FK_USUA_MAUS];


/* Create Table Comments */

EXEC sp_addextendedproperty 'MS_Description', ' CRIAÇÃO da tabela para vincular a tabela maquina com os usuarios conectados nos servidores','Schema', [dbo], 'table', [TB_MAQUINA_USUARIO_MAUS]


CREATE TABLE [dbo].[TB_COLETA_DADOS_CODA]
(
	[ID_CODA_CD_COLETA] INT NOT NULL IDENTITY (1, 1),
	[CODA_USO_CPU] VARCHAR(45)  NULL,
	[CODA_USO_MEM_RAM] INT NULL,
	[CODA_USO_DISCO] INT NULL,
	[CODA_DH_COLETA] DATETIME NULL,
	[ID_MAQU_CD_MAQUINA] INT NOT NULL
);


/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [dbo].[TB_COLETA_DADOS_CODA] 
 ADD CONSTRAINT [PK_CODA]
	PRIMARY KEY CLUSTERED ([ID_CODA_CD_COLETA] ASC);


ALTER TABLE [dbo].[TB_COLETA_DADOS_CODA]  WITH CHECK ADD CONSTRAINT [FK_MAQU_CODA] FOREIGN KEY([ID_MAQU_CD_MAQUINA])
REFERENCES [dbo].[TB_MAQUINA_MAQU] ([ID_MAQU_CD_MAQUINA])
ON DELETE CASCADE;


/* Create Table Comments */

EXEC sp_addextendedproperty 'MS_Description', 'CRIAÇÃO da tabela para COLETAR OS DADOS DA MAQUINA','Schema', [dbo], 'table', [TB_COLETA_DADOS_CODA];

/* Create Tables */

CREATE TABLE [dbo].[TB_PROCESSOS_MAQUINA_PRMA]
(
	[ID_PRMA_CD_PROCESSO] INT NOT NULL IDENTITY (1, 1),
	[PRMA_CD_PID] INT NULL,
	[PRMA_NO_PROCESSO] VARCHAR(45) NULL,
	[PRMA_USO_CPU_PROC] INT NULL,
	[PRMA_USO_RAM_PROC] INT NULL,
	[PRMA_DH_PROCESSO] DATETIME NULL,
	[ID_MAQU_CD_MAQUINA] INT NOT NULL
);

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [dbo].[TB_PROCESSOS_MAQUINA_PRMA] 
 ADD CONSTRAINT [PK_MAQU_PROCESS]
	PRIMARY KEY CLUSTERED ([ID_PRMA_CD_PROCESSO] ASC);

ALTER TABLE [dbo].[TB_PROCESSOS_MAQUINA_PRMA]  WITH CHECK ADD CONSTRAINT [FK_MAQU_PROCESS] FOREIGN KEY([ID_MAQU_CD_MAQUINA])
REFERENCES [dbo].[TB_MAQUINA_MAQU] ([ID_MAQU_CD_MAQUINA])
ON DELETE CASCADE;

/* Create Table Comments */

EXEC sp_addextendedproperty 'MS_Description', 'CRIAÇÃO da tabela para COLETAR OS PROCESSOS DA MAQUINA','Schema', [dbo], 'table', [TB_PROCESSOS_MAQUINA_PRMA];



--DROP TABLE  [dbo].[TB_MAQUINA_USUARIO_MAUS];
--
--DROP TABLE  [dbo].[TB_USUARIO_USUA];
--
--DROP TABLE  [dbo].[TB_MAQUINA_MAQU] ;
--
--DROP TABLE  [dbo].[TB_PROCESSOS_MAQUINA_PRMA];
--
--DROP TABLE  [dbo].[TB_COLETA_DADOS_CODA];

