CREATE TABLE [DBO].[TB_USUARIO_USUA]
(
	[ID_USUA_CD_USUARIO] INT NOT NULL IDENTITY (1, 1),
	[USUA_NO_USUARIO] VARCHAR(45)  NULL,
	[USUA_NO_EMAIL] VARCHAR(45) NULL,
	[USUA_CD_SENHA] VARCHAR(45) NULL,
	[USUA_NO_INDICACAO] VARCHAR(45)  NULL,
	[USUA_TP_USUARIO] BIT  NULL
);


/* CREATE PRIMARY KEYS, INDEXES, UNIQUES, CHECKS */

ALTER TABLE [DBO].[TB_USUARIO_USUA] 
 ADD CONSTRAINT [PK_USUA]
	PRIMARY KEY CLUSTERED ([ID_USUA_CD_USUARIO] ASC);


/* CREATE TABLE COMMENTS */

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', 'CRIAÇÃO DA TABELA PARA ARMAZENAR OS USUARIOS','SCHEMA', [DBO], 'TABLE', [TB_USUARIO_USUA];

-- DROP TABLE [DBO].[TB_MAQUINA_MAQU];
CREATE TABLE [DBO].[TB_MAQUINA_MAQU]
(
	[ID_MAQU_CD_MAQUINA] INT NOT NULL IDENTITY (1, 1),
	[MAQU_NO_SISTEMA_OPERACIONAL] VARCHAR(45)  NULL,
	[MAQU_NO_PROCESSADOR] VARCHAR(100)  NULL,
	[MAQU_NU_CPU_USO] VARCHAR(45) NULL,
	[MAQU_NU_MEM_RAM_TOTAL] VARCHAR(45) NULL,
	[MAQU_NU_MEM_RAM_USADA] VARCHAR(45) NULL,
	[MAQU_NU_MEM_RAM_DISPONIVEL] VARCHAR(45) NULL,
	[MAQU_NU_DISCO_TOTAL] VARCHAR(45) NULL,
	[MAQU_NU_DISCO_USADO] VARCHAR(45) NULL,
	[MAQU_NU_DISCO_DISPONIVEL] VARCHAR(45) NULL,
	[MAQU_NO_GPU] VARCHAR(45)  NULL,
	[MAQU_DS_TIPO_MAQUINA] VARCHAR(45)  NULL,
	[MAQU_NOME] VARCHAR(45)  NULL,
	[MAQU_MAC_ADDRESS] VARCHAR(45)  NULL,
);
ALTER TABLE [DBO].[TB_MAQUINA_MAQU] 
 ADD CONSTRAINT [PK_MAQU]
	PRIMARY KEY CLUSTERED ([ID_MAQU_CD_MAQUINA] ASC);

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', 'CRIAÇÃO DA TABELA PARA ARMAZENAR OS DADOS DA MAQUINA','SCHEMA', [DBO], 'TABLE', [TB_MAQUINA_MAQU];



CREATE TABLE [DBO].[TB_MAQUINA_USUARIO_MAUS]
(
	[ID_USUA_CD_USUARIO] INT NOT NULL,
	[ID_MAQU_CD_MAQUINA] INT NOT NULL,
	CONSTRAINT [PK_USUA_MAQU] PRIMARY KEY CLUSTERED
(
	[ID_USUA_CD_USUARIO] ASC,
	[ID_MAQU_CD_MAQUINA] ASC
)
	
	WITH (
			PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
		) ON [PRIMARY];




/* CREATE PRIMARY KEYS, INDEXES, UNIQUES, CHECKS */

ALTER TABLE [DBO].[TB_MAQUINA_USUARIO_MAUS]  WITH CHECK ADD  CONSTRAINT [ID_USUA_CD_USUARIO] FOREIGN KEY([ID_USUA_CD_USUARIO])
REFERENCES [DBO].[TB_USUARIO_USUA] ([ID_USUA_CD_USUARIO])
ON DELETE CASCADE;


ALTER TABLE [DBO].[TB_MAQUINA_USUARIO_MAUS]  WITH CHECK ADD CONSTRAINT [ID_MAQU_CD_MAQUINA] FOREIGN KEY([ID_MAQU_CD_MAQUINA])
REFERENCES [DBO].[TB_MAQUINA_MAQU] ([ID_MAQU_CD_MAQUINA])
ON DELETE CASCADE;


ALTER TABLE [DBO].[TB_MAQUINA_USUARIO_MAUS] CHECK CONSTRAINT [ID_USUA_CD_USUARIO];

ALTER TABLE [DBO].[TB_MAQUINA_USUARIO_MAUS] CHECK CONSTRAINT [ID_MAQU_CD_MAQUINA];


/* CREATE TABLE COMMENTS */

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', ' CRIAÇÃO DA TABELA PARA VINCULAR A TABELA MAQUINA COM OS USUARIOS CONECTADOS NOS SERVIDORES','SCHEMA', [DBO], 'TABLE', [TB_MAQUINA_USUARIO_MAUS]



CREATE TABLE [DBO].[TB_COLETA_DADOS_CODA]
(
	[ID_CODA_CD_COLETA] INT NOT NULL IDENTITY (1, 1),
	[CODA_USO_CPU] VARCHAR(45)  NULL,
	[CODA_USO_MEM_RAM] VARCHAR(45) NULL,
	[CODA_USO_DISCO] VARCHAR(45) NULL,
	[CODA_DH_COLETA] VARCHAR (45) NULL,
	[FK_MAQU_CODA] INT NOT NULL
);


/* CREATE PRIMARY KEYS, INDEXES, UNIQUES, CHECKS */

ALTER TABLE [DBO].[TB_COLETA_DADOS_CODA] 
 ADD CONSTRAINT [PK_CODA]
	PRIMARY KEY CLUSTERED ([ID_CODA_CD_COLETA] ASC);


ALTER TABLE [DBO].[TB_COLETA_DADOS_CODA]  WITH CHECK ADD CONSTRAINT [FK_MAQU_CODA] FOREIGN KEY([FK_MAQU_CODA])
REFERENCES [DBO].[TB_MAQUINA_MAQU] ([ID_MAQU_CD_MAQUINA])
ON DELETE CASCADE;


/* CREATE TABLE COMMENTS */

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', 'CRIAÇÃO DA TABELA PARA COLETAR OS DADOS DA MAQUINA','SCHEMA', [DBO], 'TABLE', [TB_COLETA_DADOS_CODA];

/* CREATE TABLES */

CREATE TABLE [DBO].[TB_PROCESSOS_MAQUINA_PRMA]
(
	[ID_PRMA_CD_PROCESSO] INT NOT NULL IDENTITY (1, 1),
	[PRMA_CD_PID] INT NULL,
	[PRMA_NO_PROCESSO] VARCHAR(45) NULL,
	[PRMA_USO_CPU_PROC] VARCHAR(45) NULL,
	[PRMA_USO_RAM_PROC] VARCHAR(45) NULL,
	[PRMA_DH_PROCESSO] VARCHAR (45) NULL,
	[FK_MAQU_PROCESS] INT NOT NULL
);

/* CREATE PRIMARY KEYS, INDEXES, UNIQUES, CHECKS */

ALTER TABLE [DBO].[TB_PROCESSOS_MAQUINA_PRMA] 
 ADD CONSTRAINT [PK_MAQU_PROCESS]
	PRIMARY KEY CLUSTERED ([ID_PRMA_CD_PROCESSO] ASC);

ALTER TABLE [DBO].[TB_PROCESSOS_MAQUINA_PRMA]  WITH CHECK ADD CONSTRAINT [FK_MAQU_PROCESS] FOREIGN KEY([FK_MAQU_PROCESS])
REFERENCES [DBO].[TB_MAQUINA_MAQU] ([ID_MAQU_CD_MAQUINA])
ON DELETE CASCADE;

/* CREATE TABLE COMMENTS */

EXEC SP_ADDEXTENDEDPROPERTY 'MS_DESCRIPTION', 'CRIAÇÃO DA TABELA PARA COLETAR OS PROCESSOS DA MAQUINA','SCHEMA', [DBO], 'TABLE', [TB_PROCESSOS_MAQUINA_PRMA];

insert into [DBO].[TB_USUARIO_USUA] VALUES ('admin','admin@admin.com','123','',0);

--INSERT INTO TB_MAQUINA_MAQU (MAQU_NO_SISTEMA_OPERACIONAL, MAQU_NO_PROCESSADOR, MAQU_NU_CPU_USO,
--MAQU_NU_MEM_RAM_TOTAL, MAQU_NU_MEM_RAM_USADA, MAQU_NU_MEM_RAM_DISPONIVEL, MAQU_NU_DISCO_TOTAL,
--MAQU_NU_DISCO_USADO, MAQU_NU_DISCO_DISPONIVEL, MAQU_NO_GPU, MAQU_DS_TIPO_MAQUINA, MAQU_NOME,
--MAQU_MAC_ADDRESS) VALUES('', '', '', '', '', '', '', '', '', '', '', '', '');

INSERT INTO TB_MAQUINA_MAQU VALUES('Linux', 'i7-7700', '54%', '16GB', '4GB', '12GB', '1TB', '400GB', '600GB', 'GTX1060', 'Servidor', 'PC-01', 'mac-address');

SELECT * FROM  [DBO].[TB_MAQUINA_MAQU] ;

SELECT * FROM [DBO].[TB_USUARIO_USUA];

SELECT * FROM [DBO].[TB_COLETA_DADOS_CODA];

SELECT * FROM [DBO].[TB_PROCESSOS_MAQUINA_PRMA];

SELECT * FROM [DBO].[TB_MAQUINA_USUARIO_MAUS];

--insert into TB_PROCESSOS_MAQUINA_PRMA values(123,'nomeproceso','usoCPU','USORAM',CURRENT_TIMESTAMP,1);


/*
DROP TABLE  [DBO].[TB_MAQUINA_USUARIO_MAUS];
DROP TABLE  [DBO].[TB_USUARIO_USUA];
DROP TABLE  [DBO].[TB_PROCESSOS_MAQUINA_PRMA];
DROP TABLE  [DBO].[TB_COLETA_DADOS_CODA];
DROP TABLE  [DBO].[TB_MAQUINA_MAQU] ;
*/




--
--
--CREATE TABLE [dbo].[Table_x](
--        [idtabelax] [int] IDENTITY(1,1) NOT NULL,
--        [descricao] [nchar](10) NULL,
--     CONSTRAINT [PK_Table_x] PRIMARY KEY CLUSTERED 
--    (
--        [idtabelax] ASC
--    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
--    ) ON [PRIMARY]
--
--    GO
--
--
--
--    CREATE TABLE [dbo].[Table_Y](
--        [idtabelaY] [int] IDENTITY(1,1) NOT NULL,
--        [descricao] [nchar](10) NULL,
--     CONSTRAINT [PK_Table_Y] PRIMARY KEY CLUSTERED 
--    (
--        [idtabelaY] ASC
--    )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
--    ) ON [PRIMARY]
--
--    GO
--
--
--CREATE TABLE [dbo].[Table_intermediaria](
--    [idtabelaX] [int] NOT NULL,
--    [idtabelaY] [int] NOT NULL,
--    [descricao] [nchar](10) NULL,
-- CONSTRAINT [PK_Table_intermediaria] PRIMARY KEY CLUSTERED 
--(
--    [idtabelaX] ASC,
--    [idtabelaY] ASC
--)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
--) ON [PRIMARY]
--
--GO
--
--ALTER TABLE [dbo].[Table_intermediaria]  WITH CHECK ADD  CONSTRAINT [FK_Table_intermediaria_Table_x] FOREIGN KEY([idtabelaX])
--REFERENCES [dbo].[Table_x] ([idtabelax])
--GO
--
--ALTER TABLE [dbo].[Table_intermediaria] CHECK CONSTRAINT [FK_Table_intermediaria_Table_x]
--GO
--
--ALTER TABLE [dbo].[Table_intermediaria]  WITH CHECK ADD  CONSTRAINT [FK_Table_intermediaria_Table_Y] FOREIGN KEY([idtabelaY])
--REFERENCES [dbo].[Table_Y] ([idtabelaY])
--GO
--
--ALTER TABLE [dbo].[Table_intermediaria] CHECK CONSTRAINT [FK_Table_intermediaria_Table_Y]
--GO
--

